#!/bin/zsh

# Go to the CMake build directory of the git repo.
build() {
    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) != 'true' ]]; then
        echo "Not in a git repository"
        return 1
    fi

    local ROOT_PATH=$(git rev-parse --show-toplevel)
    cd $ROOT_PATH
    cd cmake.bld/`uname`
}
