#!/bin/zsh

claude() {
    unset http{,s}_proxy
    unset noproxy
    env -i \
        HOME="$HOME" \
        PATH="$PATH" \
        TERM="$TERM" \
        EDITOR="$EDITOR" \
        VISUAL="$EDITOR" \
        HERDR_ENV="$HERDR_ENV" \
        GDRIVE="$GDRIVE" \
        /opt/homebrew/bin/claude "$@"
}
